<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="chirag-inspiron3558" failures="0" tests="8" name="TestCalculate" time="0.027" errors="1" timestamp="2021-01-11T01:10:39 IST" skipped="0">
  <testcase classname="TestCalculate" name="singleValueIsReplied" time="0.001"/>
  <system-out/>
  <testcase classname="TestCalculate" name="IgnoreNumberGreaterthan1000" time="0.004"/>
  <system-out/>
  <testcase classname="TestCalculate" name="twoNumbersCommaDelimitersReturnSum" time="0.002"/>
  <system-out/>
  <testcase classname="TestCalculate" name="AcceptsMultipleDelimiters" time="0.014">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Calculator.findNegativeInputs(Calculator.java:80)
at Calculator.getSum(Calculator.java:63)
at Calculator.add(Calculator.java:37)
at TestCalculate.AcceptsMultipleDelimiters(TestCalculate.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- AcceptsMultipleDelimiters -->
  <system-out/>
  <testcase classname="TestCalculate" name="twoNumbersNewLineDelimitersReturnSum" time="0.001"/>
  <system-out/>
  <testcase classname="TestCalculate" name="negativeInputReturnsException" time="0.002"/>
  <system-out/>
  <testcase classname="TestCalculate" name="threeNumbersCommaDelimitersBothWaysReturnSum" time="0.002"/>
  <system-out/>
  <testcase classname="TestCalculate" name="emptyStringReturnsZero" time="0.001"/>
  <system-out/>
</testsuite> <!-- TestCalculate -->
